name: RealisticSwimming
version: 1.0-SNAPSHOT
main: me.cryptonic.plugins.realisticswimming.Main.RealisticSwimming
api-version: 1.16
authors: [Crypt0nic, Crypt0nlc]
description: Dit is een Realistische Zwem Plugin
commands:
  rs:
    permission: rs.admin.reload
    description: 'reloads the config'
    usage: '/rs reload'
  swim:
    description: 'Enables/disables the swimming animation.'
    usage: '/swim <on/off>'
  fall:
    description: 'Enables/disables the falling animation.'
    usage: '/fall <on/off>'
permissions:
  rs.user.swim:
    default: op
  rs.user.boost:
    default: op
  rs.user.fall:
    default: op
  rs.admin.reload:
    default: op
  rs.bypass.stamina:
    default: false